# Generated by Django 6.0.dev20250713173823 on 2025-07-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('queue_name', models.CharField(max_length=100)),
                ('target', models.GenericIPAddressField()),
                ('max_limit', models.CharField(max_length=50)),
            ],
        ),
    ]
